// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// XYZ Gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

import 'package:xyz_utils/xyz_utils_non_web.dart';
import 'package:path/path.dart' as p;

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

Future<void> generateAllExports(
  String rootDirPath, [
  Set<String> pathPatterns = const {},
]) async {
  var cachedDirName = "";
  await findDartFiles(
    rootDirPath: rootDirPath,
    pathPatterns: pathPatterns,
    onFileFound: (
      _,
      __,
      final filePath,
    ) async {
      final folderName = getBaseName(rootDirPath);
      final allFilePath = p.join(rootDirPath, "all_$folderName.dart");
      if (rootDirPath != cachedDirName) {
        cachedDirName = rootDirPath;
        printGreen("Clearing `$allFilePath`...");
        await writeFile(
          allFilePath,
          [
            "// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND",
            "// See: https://github.com/robmllze/xyz_gen",
            "\n",
          ].join("\n"),
        );
      }
      if (filePath != allFilePath) {
        final fileName = getBaseName(filePath);
        final data = "export '$fileName';";

        await writeFile(
          allFilePath,
          "$data\n",
          append: true,
        );
        printGreen("Writing `$data` to `$allFilePath`...");
      } else {
        printGreen("Skipping `$filePath`...");
      }
    },
  );
}
