//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'type_color.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

extension NextPreviousTypeColor on TypeColor {
  TypeColor get next {
    final index = (this.index + 1) % TypeColor.values.length;
    return TypeColor.values[index];
  }

  TypeColor get previous {
    final index =
        (this.index - 1 + TypeColor.values.length) % TypeColor.values.length;
    return TypeColor.values[index];
  }
}

extension TranslateTypeColor on TypeColor {
  String tr() {
    return "${this.name}||types.TypeColor.$this".tr();
  }
}

extension _DeleteMe on String {
  String tr() {
    throw UnimplementedError();
  }
}
