//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'model_user.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelUser extends Model {
  //
  //
  //

  static const K_ARGS = "args";
  static const K_ID = "id";
  static const K_NAME_DATA = "name_data";

  Map<String, Map<int, Set<bool>>>? nameData;

  //
  //
  //

  ModelUser({
    String? id,
    dynamic args,
    required this.nameData,
  }) {
    this.id = id;
    this.args = args;
  }

  //
  //
  //

  ModelUser.unsafe({
    String? id,
    dynamic args,
    this.nameData,
  }) {
    assert(this.nameData != null);
    this.id = id;
    this.args = args;
  }

  //
  //
  //

  factory ModelUser.from(
    ModelUser other,
  ) {
    return ModelUser.unsafe()..updateWith(other);
  }

  //
  //
  //

  factory ModelUser.fromJsonString(
    String source,
  ) {
    try {
      final decoded = jsonDecode(source);
      return ModelUser.fromJson(decoded);
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  factory ModelUser.fromJson(
    Map<String, dynamic> input,
  ) {
    try {
      return ModelUser.unsafe(
        args: input[K_ARGS],
        id: input[K_ID]?.toString().trim().nullIfEmpty,
        nameData: letMap(input[K_NAME_DATA])
            ?.map(
              (final p0, final p1) => MapEntry(
                p0?.toString().trim().nullIfEmpty,
                letMap(p1)
                    ?.map(
                      (final p0, final p1) => MapEntry(
                        letInt(p0),
                        letSet(p1)
                            ?.map(
                              (final p0) => letBool(p0),
                            )
                            .nonNulls
                            .nullIfEmpty
                            ?.toSet()
                            .cast(),
                      ),
                    )
                    .nonNulls
                    .nullIfEmpty
                    ?.cast(),
              ),
            )
            .nonNulls
            .nullIfEmpty
            ?.cast(),
      );
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final withNulls = <String, dynamic>{
        K_ARGS: args,
        K_ID: id?.toString().trim().nullIfEmpty,
        K_NAME_DATA: nameData
            ?.map(
              (final p0, final p1) => MapEntry(
                p0?.toString().trim().nullIfEmpty,
                p1
                    ?.map(
                      (final p0, final p1) => MapEntry(
                        p0,
                        p1
                            ?.map(
                              (final p0) => p0,
                            )
                            .nonNulls
                            .nullIfEmpty
                            ?.toList(),
                      ),
                    )
                    .nonNulls
                    .nullIfEmpty,
              ),
            )
            .nonNulls
            .nullIfEmpty,
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  @override
  T empty<T extends Model>() {
    return ModelUser.unsafe() as T;
  }

  //
  //
  //

  @override
  T copy<T extends Model>() {
    return (ModelUser.unsafe()..updateWith(this)) as T;
  }

  //
  //
  //

  @override
  T copyWith<T extends Model>(
    T other,
  ) {
    if (other is ModelUser) {
      return this.copy<T>()..updateWith(other);
    }
    assert(false);
    return this.copy<T>();
  }

  //
  //
  //

  @override
  T copyWithJson<T extends Model>(
    Map<String, dynamic> other,
  ) {
    if (other.isNotEmpty) {
      return this.copy<T>()..updateWithJson(other);
    }
    return this.copy<T>();
  }

  //
  //
  //

  @override
  void updateWith<T extends Model>(
    T other,
  ) {
    if (other is ModelUser) {
      this.args = other.args ?? this.args;
      this.id = other.id ?? this.id;
      this.nameData = other.nameData ?? this.nameData;
    } else {
      assert(false);
    }
  }

  //
  //
  //

  @override
  void updateWithJson<T extends Model>(
    Map<String, dynamic> other,
  ) {
    this.updateWith(ModelUser.fromJson(other));
  }
}
