//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable require-jsdoc */

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelUser {
  //
  //
  //

  email: string;
  firstName: string | null;
  id: string;
  lastName: string | null;

  //
  //
  //

  constructor({
    email,
    firstName,
    id,
    lastName,
  }:
  {
    email: string,
    firstName: string | null,
    id: string,
    lastName: string | null,
  }) {
    this.email = email;
    this.firstName = firstName;
    this.id = id;
    this.lastName = lastName;
  }

  //
  //
  //

  toMap(): Map<string, any> {
    return new Map<string, any>([
      ['email', this.email],
      ['first_name', this.firstName],
      ['id', this.id],
      ['last_name', this.lastName],
    ]);
  }

  //
  //
  //

  static fromMap(map: Map<string, any>): ModelUser {
    return new ModelUser({
      email: map.get('email'),
      firstName: map.get('first_name'),
      id: map.get('id'),
      lastName: map.get('last_name'),
    });
  }

  //
  //
  //

  toObject(): any {
    return {
      email: this.email,
      first_name: this.firstName,
      id: this.id,
      last_name: this.lastName,
    };
  }

  //
  //
  //


  static fromObject(obj: any): ModelUser {
    return new ModelUser({
      email: obj['email'] as string,
      firstName: obj['first_name'] as string | null,
      id: obj['id'] as string,
      lastName: obj['last_name'] as string | null,
    });
  }

  //
  //
  //

  toJson(): string {
    return JSON.stringify(this.toObject());
  }

  //
  //
  //

  static fromJson(json: string): ModelUser {
    return ModelUser.fromObject(JSON.parse(json));
  }
}