//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable eol-last */
/* eslint-disable require-jsdoc */

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelUser {
  //
  //
  //

  child: ModelUser|null;
  email: string;
  firstName: string|null;
  id: string;
  lastName: string|null;

  //
  //
  //

  constructor({
    child = null,
    email,
    firstName = null,
    id,
    lastName = null,
  }:
  {
    child?: ModelUser|null,
    email: string,
    firstName?: string|null,
    id: string,
    lastName?: string|null,
  }) {
    this.child = child;
    this.email = email;
    this.firstName = firstName;
    this.id = id;
    this.lastName = lastName;
  }

  //
  //
  //

  toMap(): Map<string, any> {
    return new Map<string, any>([
      ['child', this.child?.toMap()],
      ['email', this.email],
      ['first_name', this.firstName],
      ['id', this.id],
      ['last_name', this.lastName],
    ]);
  }

  //
  //
  //

  static fromMap(map: Map<string, any>): ModelUser {
    return new ModelUser({
      child: (() => {
        const v = map.get('child');
        return v != null ? ModelUser.fromMap(v): v;
      })(),
      email: map.get('email'),
      firstName: map.get('first_name'),
      id: map.get('id'),
      lastName: map.get('last_name'),
    });
  }

  //
  //
  //

  toObject(): any {
    return {
      'child': this.child?.toObject(),
      'email': this.email,
      'first_name': this.firstName,
      'id': this.id,
      'last_name': this.lastName,
    };
  }

  //
  //
  //


  static fromObject(obj: any): ModelUser {
    return new ModelUser({
      child: (() => {
        const v = obj['child'];
        return v != null ? ModelUser.fromObject(v): v;
      })(),
      email: obj['email'],
      firstName: obj['first_name'],
      id: obj['id'],
      lastName: obj['last_name'],
    });
  }

  //
  //
  //

  toJson(): string {
    return JSON.stringify(this.toObject());
  }

  //
  //
  //

  static fromJson(json: string): ModelUser {
    return ModelUser.fromObject(JSON.parse(json));
  }
}