//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

export 'components/all_components.g.dart';
export 'components/button/button.dart';
export 'components/text/text.dart';
export 'makeups/all_makeups.g.dart';
export 'makeups/button/all_button_makeups.g.dart';
export 'makeups/text/all_text_makeups.g.dart';
export 'makeups/theme.g.dart';
export 'models/all_models.g.dart';
export 'models/model_user/model_user.dart';
export 'types/all_types.g.dart';
export 'types/type_color/type_color.dart';
export 'utils/all_utils.g.dart';
export 'utils/prep_example.dart';
