//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// --- PUBLIC FILES ---
export 'core_utils/core_utils_on_lang_extension.dart';
export 'core_utils/find_files_etc.dart';
export 'core_utils/generic_template_processor.dart';
export 'core_utils/placeholder_on_enum_extension.dart';
export 'core_utils/print_arg_parser_usage.dart';
export 'core_utils/process_comment_annots.dart';
export 'core_utils/read_code_snippets_from_markdown_file.dart';
export 'core_utils/run_command_line_app.dart';
export 'core_utils/valid_args_checker.dart';
export 'core_utils/xyz_gen_paths_etc.dart';
export 'language_support_utils/dart/dart_support.dart';
export 'language_support_utils/dart/dart_template_processor.dart';
export 'language_support_utils/lang.dart';
export 'language_support_utils/typescript/typescript_support.dart';

// --- PRIVATE FILES ---
// No private files in directory.

// --- GENERATED FILES ---
// No generated files in directory.