// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen

// ignore_for_file: dead_code
// ignore_for_file: unused_element

part of 'screen_test_1.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

const _L = "screens.ScreenTest1";
const _LOCATION = "/test_1";
const _NAME_SCREEN_CLASS = "ScreenTest1";

extension _ScreenTrExtension on String {
  String screenTr([Map<dynamic, dynamic> args = const {}]) {
    return this.splitByLastOccurrenceOf("||").join("||$_L.").tr(args);
  }
}

const LOCATION_ACCESSIBLE_ONLY_IF_SIGNED_IN_AND_VERIFIED_TEST_1 = [_LOCATION];
const LOCATION_ACCESSIBLE_ONLY_IF_SIGNED_IN_TEST_1 = [];
const LOCATION_ACCESSIBLE_ONLY_IF_SIGNED_OUT_TEST_1 = [];
const LOCATION_ACCESSIBLE_TEST_1 = [_LOCATION];
const LOCATION_NOT_REDIRECTABLE_TEST_1 = [_LOCATION];

class ScreenTest1Configuration extends MyRouteConfiguration {
  static const LOCATION = _LOCATION;
  static const L = _L;
  static const NAME_SCREEN_CLASS = _NAME_SCREEN_CLASS;

  ScreenTest1Configuration();

  ScreenTest1Configuration.from(
    MyRouteConfiguration from,
  ) : super.fromUri(
          from.uri,
          key: from.key,
          internalParameters: from.internalParameters,
        );
  
  @override
  MyRouteConfiguration to() {
    return MyRouteConfiguration.fromUri(
      this.uri,
      key: this.key,
      internalParameters: this.internalParameters,
    );
  }
}

abstract class _LogicBroker<T1 extends ScreenTest1, T2 extends _State>
    extends MyScreenLogic<ScreenTest1Configuration> {
  late final screen = super.superScreen as T1;
  late final state = super.superState as T2;
  late final configuration = this.state.configuration;
  _LogicBroker(super.superScreen, super.superState);
}