//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

export 'generators/generate_exports/all_generate_exports.g.dart';
export 'generators/generate_exports/src/app.dart';
export 'generators/generate_exports/src/generate.dart';
export 'generators/generate_for_annotation_TEST/all_generate_for_annotation_test.g.dart';
export 'generators/generate_for_annotation_TEST/src/app.dart';
export 'generators/generate_for_annotation_TEST/src/args.dart';
export 'generators/generate_for_annotation_TEST/src/generate.dart';
export 'generators/generate_for_files_TEST/all_generate_for_files_test.g.dart';
export 'generators/generate_for_files_TEST/src/app.dart';
export 'generators/generate_for_files_TEST/src/args.dart';
export 'generators/generate_for_files_TEST/src/generate.dart';
export 'generators/generate_license_headers/all_generate_license_headers.g.dart';
export 'generators/generate_license_headers/src/app.dart';
export 'generators/generate_license_headers/src/generate.dart';
export 'generators/generate_makeups/all_generate_makeups.g.dart';
export 'generators/generate_makeups/src/app.dart';
export 'generators/generate_makeups/src/args.dart';
export 'generators/generate_makeups/src/generate.dart';
export 'generators/generate_models/all_generate_models.g.dart';
export 'generators/generate_models/src/app.dart';
export 'generators/generate_models/src/generate.dart';
export 'generators/generate_models/src/loose_type_mappers.dart';
export 'generators/generate_preps/all_generate_preps.g.dart';
export 'generators/generate_preps/src/app.dart';
export 'generators/generate_preps/src/args.dart';
export 'generators/generate_preps/src/generate.dart';
export 'generators/generate_screen/all_generate_screen.g.dart';
export 'generators/generate_screen/all_generate_screens.g.dart';
export 'generators/generate_screen/src/app.dart';
export 'generators/generate_screen/src/args.dart';
export 'generators/generate_screen/src/generate.dart';
export 'generators/generate_screen_access/all_generate_screen_access.g.dart';
export 'generators/generate_screen_access/src/app.dart';
export 'generators/generate_screen_access/src/args.dart';
export 'generators/generate_screen_access/src/generate.dart';
export 'generators/generate_screen_configurations/all_generate_screen_configurations.g.dart';
export 'generators/generate_screen_configurations/src/app.dart';
export 'generators/generate_screen_configurations/src/generate.dart';
export 'utils/analyze_annotated_classes.dart';
export 'utils/basic_cmd_app.dart';
export 'utils/current_script_dir.dart';
export 'utils/dart_files.dart';
export 'utils/generate_from_templates.dart';
export 'utils/type_codes/type_codes.dart';
export 'utils/xyz_gen_lib_path.dart';
