//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// --- PUBLIC FILES ---
export '../xyz_gen.dart';
export 'data_models/model_user/model_user.dart';
export '../src/xyz/typescript_utils/typescript_support.dart';
export '../src/xyz/core_utils/preview_path.dart';
export '../src/xyz/core_utils/current_script_dir.dart';
export '../src/xyz/core_utils/core_utils_on_lang_x.dart';
export '../src/xyz/core_utils/path_explorer.dart';
export '../src/xyz/core_utils/insight_mapper.dart';
export '../src/xyz/core_utils/valid_args_checker.dart';
export '../src/xyz/core_utils/extract_code_from_markdown.dart';
export '../src/xyz/core_utils/run_command_line_app.dart';
export '../src/xyz/core_utils/lang.dart';
export '../src/xyz/core_utils/placeholder_on_enum_x.dart';
export '../src/xyz/core_utils/replacement_producer.dart';
export '../src/xyz/core_utils/combined_paths.dart';
export '../src/xyz/core_utils/find_files_etc.dart';
export '../src/xyz/core_utils/print_arg_parser_usage.dart';
export '../src/xyz/core_utils/generator_converger.dart';
export '../src/xyz/core_utils/split_arg.dart';
export '../src/xyz/core_utils/xyz_gen_paths_etc.dart';
export '../src/xyz/core_utils/mappers_etc.dart';
export '../src/xyz/core_utils/process_comment_annots.dart';
export '../src/xyz/core_utils/replacements.dart';
export '../src/xyz/core_utils/insights/insight.dart';
export '../src/xyz/core_utils/insights/class_insight.dart';
export '../src/xyz/dart_utils/dart_type_code_mapper.dart';
export '../src/xyz/dart_utils/dart_annotated_class_analyzer.dart';
export '../src/xyz/dart_utils/dart_field.dart';
export '../src/xyz/dart_utils/decompose_dart_collection_type.dart';
export '../src/xyz/dart_utils/dart_support.dart';
export '../src/xyz/dart_utils/dart_loose_type_mappers.dart';
export '../src/xyz/dart_utils/dart_from_record_on_dart_object_x.dart';
export '../src/utils/analyze_annotated_enums.dart';
export '../src/generators/generate_directives_for_dart/src/generate_directives_for_dart.dart';
export '../src/generators/generate_directives_for_dart/src/run_generate_directives_for_dart_app.dart';
export '../src/generators/generate_models_for_dart/src/run_generate_models_for_dart_app.dart';
export '../src/generators/generate_models_for_dart/src/generate_models_for_dart_from_annotations.dart';
export '../src/generators/generate_exports/src/run_generate_exports_for_dart_app.dart';
export '../src/generators/generate_exports/src/generate_exports.dart';
export '../src/xyz/typescript_utils/typescript_support.dart';
export '../src/xyz/core_utils/preview_path.dart';
export '../src/xyz/core_utils/current_script_dir.dart';
export '../src/xyz/core_utils/core_utils_on_lang_x.dart';
export '../src/xyz/core_utils/path_explorer.dart';
export '../src/xyz/core_utils/insight_mapper.dart';
export '../src/xyz/core_utils/valid_args_checker.dart';
export '../src/xyz/core_utils/extract_code_from_markdown.dart';
export '../src/xyz/core_utils/run_command_line_app.dart';
export '../src/xyz/core_utils/lang.dart';
export '../src/xyz/core_utils/placeholder_on_enum_x.dart';
export '../src/xyz/core_utils/replacement_producer.dart';
export '../src/xyz/core_utils/combined_paths.dart';
export '../src/xyz/core_utils/find_files_etc.dart';
export '../src/xyz/core_utils/print_arg_parser_usage.dart';
export '../src/xyz/core_utils/generator_converger.dart';
export '../src/xyz/core_utils/split_arg.dart';
export '../src/xyz/core_utils/xyz_gen_paths_etc.dart';
export '../src/xyz/core_utils/mappers_etc.dart';
export '../src/xyz/core_utils/process_comment_annots.dart';
export '../src/xyz/core_utils/replacements.dart';
export '../src/xyz/core_utils/insights/insight.dart';
export '../src/xyz/core_utils/insights/class_insight.dart';
export '../src/xyz/dart_utils/dart_type_code_mapper.dart';
export '../src/xyz/dart_utils/dart_annotated_class_analyzer.dart';
export '../src/xyz/dart_utils/dart_field.dart';
export '../src/xyz/dart_utils/decompose_dart_collection_type.dart';
export '../src/xyz/dart_utils/dart_support.dart';
export '../src/xyz/dart_utils/dart_loose_type_mappers.dart';
export '../src/xyz/dart_utils/dart_from_record_on_dart_object_x.dart';
export '../src/utils/analyze_annotated_enums.dart';
export '../src/generators/generate_directives_for_dart/src/generate_directives_for_dart.dart';
export '../src/generators/generate_directives_for_dart/src/run_generate_directives_for_dart_app.dart';
export '../src/generators/generate_models_for_dart/src/run_generate_models_for_dart_app.dart';
export '../src/generators/generate_models_for_dart/src/generate_models_for_dart_from_annotations.dart';
export '../src/generators/generate_exports/src/run_generate_exports_for_dart_app.dart';
export '../src/generators/generate_exports/src/generate_exports.dart';

// --- PRIVATE FILES ---
// export '../_common.dart';
// export '../src/xyz/typescript_utils/_ts_replacements.dart';
// export '../src/generators/generate_models_for_dart/src/_utils/_generator_converger.dart';
// export '../src/generators/generate_models_for_dart/src/_utils/_strip_special_syntax_from_field_type.dart';
// export '../src/generators/generate_models_for_dart/src/_utils/_extract_class_insights_from_dart_file.dart';
// export '../src/generators/generate_models_for_dart/src/_utils/_insight_mappers.dart';
// export '../src/xyz/typescript_utils/_ts_replacements.dart';
// export '../src/generators/generate_models_for_dart/src/_utils/_generator_converger.dart';
// export '../src/generators/generate_models_for_dart/src/_utils/_strip_special_syntax_from_field_type.dart';
// export '../src/generators/generate_models_for_dart/src/_utils/_extract_class_insights_from_dart_file.dart';
// export '../src/generators/generate_models_for_dart/src/_utils/_insight_mappers.dart';

// --- GENERATED FILES ---
// export '_all_src_test.g.dart';
// export 'data_models/model_user/_model_user.g.dart';
// export '../src/_all_src.g.dart';
// export '../src/xyz/_all_xyz.g.dart';
// export '../src/generators/generate_directives_for_dart/src/_all_src.g.dart';
// export '../src/generators/generate_models_for_dart/src/_all_src.g.dart';
// export '../src/generators/generate_exports/src/_all_src.g.dart';
// export '../src/_all_src.g.dart';
// export '../src/xyz/_all_xyz.g.dart';
// export '../src/generators/generate_directives_for_dart/src/_all_src.g.dart';
// export '../src/generators/generate_models_for_dart/src/_all_src.g.dart';
// export '../src/generators/generate_exports/src/_all_src.g.dart';