//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

import '../all_lib.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class GeneratedTheme {
  //
  //
  //

  late FButtonMakeup buttonDefault;
  late FButtonMakeup buttonSmall;
  late FButtonMakeup buttonMedium;
  late FButtonMakeup buttonLarge;
  late FTextMakeup textDefault;
  late FTextMakeup textSmall;
  late FTextMakeup textMedium;
  late FTextMakeup textLarge;

  //
  //
  //

  void init() {
    this.buttonDefault = buttonDefaultMakeup;
    this.buttonSmall = buttonSmallMakeup;
    this.buttonMedium = buttonMediumMakeup;
    this.buttonLarge = buttonLargeMakeup;
    this.textDefault = textDefaultMakeup;
    this.textSmall = textSmallMakeup;
    this.textMedium = textMediumMakeup;
    this.textLarge = textLargeMakeup;
  }
}
