// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// XYZ Gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

// ignore_for_file: non_constant_identifier_names

import 'utils/file_io.dart';
import 'utils/find_files.dart';
import 'utils/helpers.dart';
import 'package:path/path.dart' as p;

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

Future<void> generateAllExports(
  String startingDirPath,
  Set<String> pathPatterns,
) async {
  var cachedDirName = "";
  await findFiles(
    startingDirPath: startingDirPath,
    pathPatterns: pathPatterns,
    onFileFound: (
      final dirName,
      final folderName,
      final filePath,
    ) async {
      final allFilePath = p.join(dirName, "all_$folderName.dart");
      if (dirName != cachedDirName) {
        cachedDirName = dirName;
        print("[generateAllExports] Clearing `$allFilePath`...");
        await writeFile(
          allFilePath,
          [
            "// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND",
            "// See: https://github.com/robmllze/xyz_gen",
            "\n",
          ].join("\n"),
        );
      }
      if (filePath != allFilePath) {
        final fileName = getBaseName(filePath);
        final data = "export '$fileName';";
        print("[generateAllExports] Writing `$data` to `$allFilePath`...");
        await writeFile(
          allFilePath,
          "$data\n",
          append: true,
        );
      } else {
        print("[generateAllExports] Skipping `$filePath`...");
      }
    },
  );
}
