//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// --- PUBLIC FILES ---
export 'core_utils/combined_dir_paths.dart';
export 'core_utils/core_utils_on_lang_x.dart';
export 'core_utils/current_script_dir.dart';
export 'core_utils/find_files_etc.dart';
export 'core_utils/lang.dart';
export 'core_utils/mappers_etc.dart';
export 'core_utils/placeholder_on_enum_x.dart';
export 'core_utils/print_arg_parser_usage.dart';
export 'core_utils/process_comment_annots.dart';
export 'core_utils/read_code_snippets_from_markdown_file.dart';
export 'core_utils/run_command_line_app.dart';
export 'core_utils/split_arg.dart';
export 'core_utils/steps/generator_converger.dart';
export 'core_utils/steps/insight_mapper.dart';
export 'core_utils/steps/insights/class_insight.dart';
export 'core_utils/steps/insights/insight.dart';
export 'core_utils/steps/replacement_producer.dart';
export 'core_utils/template_integrator.dart';
export 'core_utils/valid_args_checker.dart';
export 'core_utils/xyz_gen_paths_etc.dart';
export 'dart_utils/dart_annotated_class_analyzer.dart';
export 'dart_utils/dart_field.dart';
export 'dart_utils/dart_from_record_on_dart_object_x.dart';
export 'dart_utils/dart_loose_type_mappers.dart';
export 'dart_utils/dart_support.dart';
export 'dart_utils/dart_type_code_mapper.dart';
export 'dart_utils/decompose_dart_collection_type.dart';
export 'typescript_utils/typescript_support.dart';

// --- PRIVATE FILES ---
// export 'typescript_utils/_ts_replacements.dart';

// --- GENERATED FILES ---
// export '_all_xyz.g.dart';