// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

export '_makeup.g.dart';
export '_default_my_widget_makeup.dart';
export '_primary_my_widget_makeup.dart';
export '_secondary_my_widget_makeup.dart';
