// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen

// ignore_for_file: dead_code
// ignore_for_file: unused_element
// ignore_for_file: constant_identifier_names

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class MyWidgetMakeup {
  //
  //
  //

  int? value;
  String colorCode;

  //
  //
  //

  MyWidgetMakeup({
    this.value,
    required this.colorCode,
  });

  //
  //
  //

  MyWidgetMakeup copyWith({
    int? value,
    String? colorCode,
  }) {
    return MyWidgetMakeup(
      value: value ?? this.value,
      colorCode: colorCode ?? this.colorCode,
    );
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef FMyWidgetMakeup = MyWidgetMakeup Function();
