// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN
// See: https://github.com/robmllze/xyz_gen
//
// This file is proprietary. No external sharing or distribution.
// Refer to README.md and the project's LICENSE file for details.
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

part of 'screen_home.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class _Logic extends _LogicBroker<ScreenHome, _State> {
  //
  //
  //

  _Logic(super.screen, super.state);

  //
  //
  //

  final pCounter = Pod<int>(-1);

  //
  //
  //

  void incrementCounter() {
    this.pCounter.update((final value) => value + 1);
  }

  //
  //
  //

  @override
  void initLogic() {
    this.pCounter.set(0);
    super.initLogic();
  }

  //
  //
  //

  @override
  void dispose() {
    // Be sure to dispose all pods here.
    this.pCounter.dispose();
    super.dispose();
  }
}
