// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen

// ignore_for_file: dead_code
// ignore_for_file: unused_element
// ignore_for_file: constant_identifier_names

part of 'model_user.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelUser extends ModelUserUtils {
  //
  //
  //

  static const K_FIRST_NAME = "first_name";
  static const K_LAST_NAME = "last_name";
  static const K_DISPLAY_NAME = "display_name";
  static const K_ID = "id";
  static const K_ARGS = "args";

  String firstName;
  String lastName;
  String displayName;
  String? id;
  dynamic args;

  //
  //
  //

  ModelUser({
    required this.firstName,
    required this.lastName,
    required this.displayName,
    this.id,
    this.args,
  });

  /*
  factory ModelUser.fromJMap(Map<String, dynamic> input) {
    try {
      return ModelUser(
        id: input["id"],
        args: input["args"],  
        firstName: input["first_name"],
lastName: input["last_name"],
displayName: input["display_name"],
id: input["id"],
args: input["args"],
      );
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }
  */

  //
  //
  //

  @override
  Map<String, dynamic> toJMap() {
    try {
      return {};
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  @override
  List<Object> get props => [
        this.firstName,
        this.lastName,
        this.displayName,
        this.id,
        this.args,
      ].nonNulls.toList();

  //
  //
  //

  @override
  String toString() => this.toJMap().toString();
}
