// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class MyWidgetMakeup {
  //
  //
  //

  int? value;
  String? colorCode;

  //
  //
  //

  MyWidgetMakeup({
    this.value,
    this.colorCode,
  });

  //
  //
  //

  MyWidgetMakeup copyWith({
    int? value,
    String? colorCode,
  }) {
    return MyWidgetMakeup(
      value: value ?? this.value,
      colorCode: colorCode ?? this.colorCode,
    );
  }
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef FMyWidgetMakeup = MyWidgetMakeup Function();
