// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN
// See: https://github.com/robmllze/xyz_gen
//
// This file is proprietary. No external sharing or distribution.
// Refer to README.md and the project's LICENSE file for details.
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

import 'package:flutter/material.dart';
import 'package:xyz_gen/generate_screen_configurations/annotation.dart';

import '/all.dart';

part '_screen_hello.g.dart';
part '_screen_hello.logic.dart';
part '_screen_hello.logic.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

@GenerateScreenConfiguration()
class ScreenHello extends MyScreen {
  //
  //
  //

  ScreenHello(MyRouteConfiguration configuration)
      : super(
          configuration,
        );

  //
  //
  //

  // Do not modify.
  @override
  _State createState() => _State();

  //
  //
  //

  // Do not modify.
  @override
  _Logic createLogic(final screen, final state) => _Logic(screen, state);
}
